const publications = [
  {
    "key": "MGXQ6KIR",
    "title": "Cosmological analysis of the DESI DR1 Lyα 1D power spectrum",
    "year": "2026",
    "type": "journalArticle",
    "authors": [
      "J. Chaves-Montero",
      "A. Font-Ribera",
      "P. McDonald",
      "E. Armengaud",
      "D. Chebat",
      "C. Garcia-Quintero",
      "N.G. Karaçaylı",
      "C. Ravoux",
      "S. Satyavolu",
      "N. Schöneberg",
      "M. Walther",
      "J. Aguilar",
      "S. Ahlen",
      "S. Bailey",
      "D. Bianchi",
      "D. Brooks",
      "T. Claybaugh",
      "A. Cuceu",
      "A. de la Macorra",
      "P. Doel",
      "S. Ferraro",
      "J.E. Forero-Romero",
      "E. Gaztañaga",
      "S.Gontcho A. Gontcho",
      "A.X. Gonzalez-Morales",
      "G. Gutierrez",
      "J. Guy",
      "C. Hahn",
      "H.K. Herrera-Alcantar",
      "K. Honscheid",
      "M. Ishak",
      "R. Joyce",
      "S. Juneau",
      "D. Kirkby",
      "A. Kremin",
      "O. Lahav",
      "C. Lamman",
      "M. Landriau",
      "J.M. Le Goff",
      "L. Le Guillou",
      "A. Leauthaud",
      "M.E. Levi",
      "M. Manera",
      "P. Martini",
      "A. Meisner",
      "R. Miquel",
      "J. Moustakas",
      "S. Nadathur",
      "G. Niz",
      "N. Palanque-Delabrouille",
      "W.J. Percival",
      "F. Prada",
      "I. Pérez-Ràfols",
      "G. Rossi",
      "E. Sanchez",
      "D. Schlegel",
      "M. Schubnell",
      "H. Seo",
      "J. Silber",
      "D. Sprayberry",
      "T. Tan",
      "G. Tarlé",
      "B.A. Weaver",
      "C. Yèche",
      "R. Zhou",
      "H. Zou"
    ],
    "venue": "Journal of Cosmology and Astroparticle Physics",
    "doi": "10.1088/1475-7516/2026/06/040",
    "url": "https://doi.org/10.1088/1475-7516/2026/06/040",
    "summary": "This analysis interprets DESI DR1 P1D with a hydrodynamical-simulation emulator plus corrections for astrophysical contaminants and instrumental systematics, validated blindly on mocks and analysis variants. It measures the amplitude and slope of the z=3 linear matter spectrum and, with BAO and CMB data, improves constraints on relativistic species and spectral running, especially the running of running."
  },
  {
    "key": "P6FK5EYP",
    "title": "Cosmological constraints from the small scale clustering of Emission Line Galaxies",
    "year": "2026",
    "type": "webpage",
    "authors": [
      "Sara Ortega-Martinez",
      "Raul E. Angulo",
      "Sergio Contreras",
      "Jonás Chaves-Montero",
      "Matteo Zennaro",
      "Sownak Bose",
      "Boryana Hadzhiyska",
      "César Hernández-Aguayo",
      "Lars Hernquist",
      "Volker Springel"
    ],
    "venue": "arXiv.org",
    "doi": "",
    "url": "https://arxiv.org/abs/2604.19449v1",
    "summary": "The paper applies SHAMe-SF to DESI One-Percent ELG clustering down to 0.3 h^-1 Mpc and validates unbiased Ωmh² and σ8 recovery on two MillenniumTNG mocks. Small scales below 0.8 h^-1 Mpc are essential to control projection effects; the tiny DESI sample already gives about 6% constraints, including σ8=0.81 (+0.05/-0.06)."
  },
  {
    "key": "M6929L9E",
    "title": "DESI DR2 Results IV: Alcock-Paczyński Measurements from the Lyman Alpha Forest and Cosmological Constraints",
    "year": "2026",
    "type": "preprint",
    "authors": [
      "DESI Collaboration",
      "A. G. Adame",
      "J. Aguilar",
      "S. Ahlen",
      "O. Alves",
      "A. Anand",
      "U. Andrade",
      "E. Armengaud",
      "S. Avila",
      "A. Aviles",
      "P. Bansal",
      "A. Bault",
      "J. R. Bermejo-Climent",
      "F. Beutler",
      "D. Bianchi",
      "C. Blake",
      "S. Blasby",
      "M. Bonici",
      "S. Brieden",
      "A. Brodzeller",
      "D. Brooks",
      "A. Carnero Rosell",
      "K. Carrion",
      "L. Casas",
      "F. J. Castander",
      "E. Chaussidon",
      "J. Chaves-Montero",
      "D. Chebat",
      "X. Chen",
      "Z. Chen",
      "Y. Cho",
      "T. Claybaugh",
      "A. Cuceu",
      "T. M. Davis",
      "K. S. Dawson",
      "R. de Belsunce",
      "A. de la Macorra",
      "J. Della Costa",
      "A. Dey",
      "M. Doshi",
      "H. Ebina",
      "D. J. Eisenstein",
      "W. Elbers",
      "G. Farren",
      "V. A. Fawcett",
      "E. Fernández-García",
      "S. Ferraro",
      "A. Font-Ribera",
      "D. Forero-Sánchez",
      "J. E. Forero-Romero",
      "C. S. Frenk",
      "G. Gambardella",
      "C. Garcia-Quintero",
      "L. H. Garrison",
      "H. Gil-Marín",
      "S. Gontcho A. Gontcho",
      "A. X. Gonzalez-Morales",
      "C. Gordon",
      "D. Green",
      "R. Gsponer",
      "G. Gutierrez",
      "J. Guy",
      "B. Hadzhiyska",
      "C. Hahn",
      "S. He",
      "M. Herbold",
      "H. K. Herrera-Alcantar",
      "M.-F. Ho",
      "K. Honscheid",
      "J. Hou",
      "D. Huterer",
      "V. Iršič",
      "M. Ishak",
      "J.-Q. Jiang",
      "S. Jos",
      "S. Juneau",
      "N. V. Kamble",
      "N. G. Karaçaylı",
      "T. Karim",
      "D. Kirkby",
      "A. Kremin",
      "A. Krolewski",
      "O. Lahav",
      "C. Lamman",
      "M. Landriau",
      "J. Lasker",
      "J. M. Le Goff",
      "L. Le Guillou",
      "A. Leauthaud",
      "Q. Li",
      "W. Liu",
      "K. Lodha",
      "Y. Luo",
      "O. Manasoiu",
      "M. Manera",
      "P. Martini",
      "M. Maus",
      "A. Meisner",
      "R. Miquel",
      "J. Morawetz",
      "J. Moustakas",
      "E. Mueller",
      "P. Mukherjee",
      "A. Muñoz-Gutiérrez",
      "A. D. Myers",
      "S. Nadathur",
      "J. Najita",
      "G. Niz",
      "H. E. Noriega",
      "E. Paillas",
      "N. Palanque-Delabrouille",
      "J. Pan",
      "M. P. Ibanez",
      "W. J. Percival",
      "A. Porredon",
      "F. Prada",
      "H. Pulido-Hernández",
      "A. Pérez-Fernández",
      "I. Pérez-Ràfols",
      "A. Raichoor",
      "M. Rashkovetskyi",
      "J. Ratajczak",
      "C. Ravoux",
      "A. Robertson",
      "A. Rocher",
      "J. Rohlf",
      "A. J. Ross",
      "G. Rossi",
      "R. Ruggeri",
      "M. F. Ruiz-Herrera Bernal",
      "L. Samushia",
      "E. Sanchez",
      "C. Saulder",
      "D. Schlegel",
      "H. Seo",
      "A. Shafieloo",
      "R. Sharples",
      "J. Silber",
      "F. Sinigaglia",
      "M. Siudek",
      "T. Tan",
      "G. Tarlé",
      "W. Turner",
      "R. Vaisakh",
      "M. Vargas-Magaña",
      "B. A. Weaver",
      "M. Wolfson",
      "H. Yang",
      "J. Yu",
      "C. Yèche",
      "H. Zhang",
      "Y. Zhang",
      "R. Zhao",
      "R. Zhou"
    ],
    "venue": "",
    "doi": "10.48550/arXiv.2607.27410",
    "url": "http://arxiv.org/abs/2607.27410",
    "summary": "DESI DR2 full-shape Lyα correlations constrain the Alcock–Paczyński effect to 1% at z=2.33, twice as tightly as BAO from the same data. Joint AP and BAO give precise radial and transverse distances and H0=66.5±1.3 km/s/Mpc with a nucleosynthesis prior; adding the result modestly changes DESI–CMB consistency and retains a multi-probe preference for evolving dark energy."
  },
  {
    "key": "VRILPD7H",
    "title": "J-PAS: Semi-Supervised Sim-to-Obs Transfer for Robust Star--Galaxy--Quasar Classification",
    "year": "2026",
    "type": "preprint",
    "authors": [
      "Daniel López-Cano",
      "L. Raul Abramo",
      "L. Nakazono",
      "I. Pérez-Ràfols",
      "G. Martínez-Solaeche",
      "J. Chaves-Montero",
      "Matthew M. Pieri",
      "Jailson Alcaniz",
      "Narciso Benitez",
      "Silvia Bonoli",
      "Saulo Carneiro",
      "Javier Cenarro",
      "David Cristóbal-Hornillos",
      "Simone Daflon",
      "Renato Dupke",
      "Alessandro Ederoclite",
      "Rosa González Delgado",
      "Antonio Hernán-Caballero",
      "Carlos Hernández-Monteagudo",
      "Jifeng Liu",
      "Carlos López-Sanjuan",
      "Antonio Marín-Franch",
      "Claudia Mendes de Oliveira",
      "Mariano Moles",
      "Fernando Roig",
      "Laerte Sodré",
      "Keith Taylor",
      "Jesús Varela",
      "Héctor Vázquez Ramió",
      "Jose Vilchez",
      "Javier Zaragoza-Cardiel"
    ],
    "venue": "",
    "doi": "10.48550/arXiv.2602.13902",
    "url": "http://arxiv.org/abs/2602.13902",
    "summary": "The paper addresses simulation-to-observation domain shift by pretraining a four-class photospectral classifier on DESI-to-J-PAS mocks and adapting it with a small labelled J-PAS sample. Semi-supervised adaptation reaches macro-F1=0.82 and improves high-redshift-quasar F1 to 0.66, outperforming both target-only and mocks-only baselines."
  },
  {
    "key": "6GEP8F7G",
    "title": "Lyman-$α$ forest holography: 3D predictions from 1D measurements",
    "year": "2026",
    "type": "preprint",
    "authors": [
      "J. Chaves-Montero",
      "A. Font-Ribera",
      "J. Aguilar",
      "S. Ahlen",
      "E. Armengaud",
      "A. Aviles",
      "F. Beutler",
      "D. Bianchi",
      "S. Blasby",
      "D. Brooks",
      "K. Carrion",
      "Z. Chen",
      "T. Claybaugh",
      "A. Cuceu",
      "A. de la Macorra",
      "A. Dey",
      "P. Doel",
      "W. Elbers",
      "S. Ferraro",
      "L. Flores",
      "J. E. Forero-Romero",
      "E. Gaztañaga",
      "S. Gontcho A. Gontcho",
      "D. Gonzalez",
      "A. X. Gonzalez-Morales",
      "R. Gsponer",
      "G. Gutierrez",
      "C. Hahn",
      "M. Herbold",
      "H. K. Herrera-Alcantar",
      "K. Honscheid",
      "M. Ishak",
      "S. Juneau",
      "N. V. Kamble",
      "D. Kirkby",
      "A. Kremin",
      "A. Lambert",
      "M. Landriau",
      "L. Le Guillou",
      "K. Lodha",
      "Z. Lukić",
      "M. Manera",
      "P. Martini",
      "A. Meisner",
      "R. Miquel",
      "P. Mukherjee",
      "A. Muñoz-Gutiérrez",
      "S. Nadathur",
      "H. E. Noriega",
      "E. Paillas",
      "N. Palanque-Delabrouille",
      "W. J. Percival",
      "C. Poppett",
      "F. Prada",
      "H. Pulido-Hernández",
      "I. Pérez-Ràfols",
      "C. Ravoux",
      "J. Rohlf",
      "A. J. Rosado-Marín",
      "G. Rossi",
      "R. Ruggeri",
      "M. F. Ruiz-Herrera Bernal",
      "E. Sanchez",
      "C. Saulder",
      "D. Schlegel",
      "M. Schubnell",
      "F. Sinigaglia",
      "G. Tarlé",
      "W. Turner",
      "B. A. Weaver",
      "H. Zhang"
    ],
    "venue": "",
    "doi": "10.48550/arXiv.2607.27413",
    "url": "http://arxiv.org/abs/2607.27413",
    "summary": "Using ForestFlow, the paper maps DESI P1D constraints into predictions for three-dimensional Lyα clustering from linear to nonlinear scales. The predictions reproduce DESI BAO-scale measurements, furnish nonlinear priors for the DR2 full-shape analysis, and pass an independent ACCEL-2 hydrodynamical test; P1D and BAO constrain bias–growth combinations with complementary degeneracies."
  },
  {
    "key": "CR8Z7BW7",
    "title": "Machine Learning Techniques for Astrophysics and Cosmology: Lyman-$\\alpha$ forest",
    "year": "2026",
    "type": "webpage",
    "authors": [
      "Jonás Chaves-Montero"
    ],
    "venue": "arXiv.org",
    "doi": "",
    "url": "https://arxiv.org/abs/2605.22489v1",
    "summary": "This chapter reviews machine-learning applications to Lyα-forest science, from absorber detection and quasar-continuum reconstruction to hydrodynamical emulation, simulation-based inference, field-level analysis, and three-dimensional density reconstruction. It relates these tools to IGM thermal history, reionization, expansion, structure growth, neutrinos, and dark matter."
  },
  {
    "key": "FN7XZR2H",
    "title": "DESI DR1 Ly$α$ forest: 3D full-shape analysis and cosmological constraints",
    "year": "2025",
    "type": "preprint",
    "authors": [
      "Andrei Cuceu",
      "Hiram K. Herrera-Alcantar",
      "Calum Gordon",
      "César Ramírez-Pérez",
      "E. Armengaud",
      "A. Font-Ribera",
      "J. Guy",
      "B. Joachimi",
      "P. Martini",
      "S. Nadathur",
      "I. Pérez-Ràfols",
      "J. Rich",
      "J. Aguilar",
      "S. Ahlen",
      "A. Anand",
      "S. Bailey",
      "A. Bault",
      "D. Bianchi",
      "A. Brodzeller",
      "D. Brooks",
      "J. Chaves-Montero",
      "T. Claybaugh",
      "K. S. Dawson",
      "A. de la Macorra",
      "J. Della Costa",
      "P. Doel",
      "S. Ferraro",
      "J. E. Forero-Romero",
      "E. Gaztañaga",
      "S. Gontcho A. Gontcho",
      "A. X. Gonzalez-Morales",
      "D. Green",
      "G. Gutierrez",
      "C. Hahn",
      "M. Herbold",
      "K. Honscheid",
      "V. Iršič",
      "M. Ishak",
      "R. Joyce",
      "N. G. Karaçaylı",
      "D. Kirkby",
      "T. Kisner",
      "A. Kremin",
      "O. Lahav",
      "A. Lambert",
      "C. Lamman",
      "M. Landriau",
      "J. M. Le Goff",
      "L. Le Guillou",
      "M. E. Levi",
      "M. Manera",
      "A. Meisner",
      "R. Miquel",
      "J. Moustakas",
      "A. Muñoz-Gutiérrez",
      "J. A. Newman",
      "G. Niz",
      "N. Palanque-Delabrouille",
      "W. J. Percival",
      "Matthew M. Pieri",
      "C. Poppett",
      "F. Prada",
      "C. Ravoux",
      "G. Rossi",
      "E. Sanchez",
      "D. Schlegel",
      "M. Schubnell",
      "H. Seo",
      "J. Silber",
      "F. Sinigaglia",
      "D. Sprayberry",
      "T. Tan",
      "G. Tarlé",
      "M. Walther",
      "B. A. Weaver",
      "C. Yèche",
      "R. Zhou",
      "H. Zou"
    ],
    "venue": "",
    "doi": "10.48550/arXiv.2509.15308",
    "url": "http://arxiv.org/abs/2509.15308",
    "summary": "The paper fits the broadband shapes of DESI DR1 Lyα auto- and quasar cross-correlations, with blinded mock and split validation. It measures DM/DH at z=2.33 to about 1.6%, 2.4 times tighter than BAO alone, and combines with DR2 BAO to infer H0=68.3±1.6 km/s/Mpc in ΛCDM; fσ8 is reported but excluded from cosmology because mock validation is insufficient."
  },
  {
    "key": "Q7DI85LJ",
    "title": "DESI DR2 Results II: Measurements of Baryon Acoustic Oscillations and Cosmological Constraints",
    "year": "2025",
    "type": "preprint",
    "authors": [
      "DESI Collaboration",
      "M. Abdul Karim",
      "J. Aguilar",
      "S. Ahlen",
      "S. Alam",
      "L. Allen",
      "C. Allende Prieto",
      "O. Alves",
      "A. Anand",
      "U. Andrade",
      "E. Armengaud",
      "A. Aviles",
      "S. Bailey",
      "C. Baltay",
      "P. Bansal",
      "A. Bault",
      "J. Behera",
      "S. BenZvi",
      "D. Bianchi",
      "C. Blake",
      "S. Brieden",
      "A. Brodzeller",
      "D. Brooks",
      "E. Buckley-Geer",
      "E. Burtin",
      "R. Calderon",
      "R. Canning",
      "A. Carnero Rosell",
      "P. Carrilho",
      "L. Casas",
      "F. J. Castander",
      "R. Cereskaite",
      "M. Charles",
      "E. Chaussidon",
      "J. Chaves-Montero",
      "D. Chebat",
      "X. Chen",
      "T. Claybaugh",
      "S. Cole",
      "A. P. Cooper",
      "A. Cuceu",
      "K. S. Dawson",
      "A. de la Macorra",
      "A. de Mattia",
      "N. Deiosso",
      "J. Della Costa",
      "R. Demina",
      "A. Dey",
      "B. Dey",
      "Z. Ding",
      "P. Doel",
      "J. Edelstein",
      "D. J. Eisenstein",
      "W. Elbers",
      "P. Fagrelius",
      "K. Fanning",
      "E. Fernández-García",
      "S. Ferraro",
      "A. Font-Ribera",
      "J. E. Forero-Romero",
      "C. S. Frenk",
      "C. Garcia-Quintero",
      "L. H. Garrison",
      "E. Gaztañaga",
      "H. Gil-Marín",
      "S. Gontcho A. Gontcho",
      "D. Gonzalez",
      "A. X. Gonzalez-Morales",
      "C. Gordon",
      "D. Green",
      "G. Gutierrez",
      "J. Guy",
      "B. Hadzhiyska",
      "C. Hahn",
      "S. He",
      "M. Herbold",
      "H. K. Herrera-Alcantar",
      "M. Ho",
      "K. Honscheid",
      "C. Howlett",
      "D. Huterer",
      "M. Ishak",
      "S. Juneau",
      "N. V. Kamble",
      "N. G. Karaçaylı",
      "R. Kehoe",
      "S. Kent",
      "A. G. Kim",
      "D. Kirkby",
      "T. Kisner",
      "S. E. Koposov",
      "A. Kremin",
      "A. Krolewski",
      "O. Lahav",
      "C. Lamman",
      "M. Landriau",
      "D. Lang",
      "J. Lasker",
      "J. M. Le Goff",
      "L. Le Guillou",
      "A. Leauthaud",
      "M. E. Levi",
      "Q. Li",
      "T. S. Li",
      "K. Lodha",
      "M. Lokken",
      "F. Lozano-Rodríguez",
      "C. Magneville",
      "M. Manera",
      "P. Martini",
      "W. L. Matthewson",
      "A. Meisner",
      "J. Mena-Fernández",
      "A. Menegas",
      "T. Mergulhão",
      "R. Miquel",
      "J. Moustakas",
      "A. Muñoz-Gutiérrez",
      "D. Muñoz-Santos",
      "A. D. Myers",
      "S. Nadathur",
      "K. Naidoo",
      "L. Napolitano",
      "J. A. Newman",
      "G. Niz",
      "H. E. Noriega",
      "E. Paillas",
      "N. Palanque-Delabrouille",
      "J. Pan",
      "J. Peacock",
      "Marcos Pellejero Ibanez",
      "W. J. Percival",
      "A. Pérez-Fernández",
      "I. Pérez-Ràfols",
      "M. M. Pieri",
      "C. Poppett",
      "F. Prada",
      "D. Rabinowitz",
      "A. Raichoor",
      "C. Ramírez-Pérez",
      "M. Rashkovetskyi",
      "C. Ravoux",
      "J. Rich",
      "A. Rocher",
      "C. Rockosi",
      "J. Rohlf",
      "J. O. Román-Herrera",
      "A. J. Ross",
      "G. Rossi",
      "R. Ruggeri",
      "V. Ruhlmann-Kleider",
      "L. Samushia",
      "E. Sanchez",
      "N. Sanders",
      "D. Schlegel",
      "M. Schubnell",
      "H. Seo",
      "A. Shafieloo",
      "R. Sharples",
      "J. Silber",
      "F. Sinigaglia",
      "D. Sprayberry",
      "T. Tan",
      "G. Tarlé",
      "P. Taylor",
      "W. Turner",
      "L. A. Ureña-López",
      "R. Vaisakh",
      "F. Valdes",
      "G. Valogiannis",
      "M. Vargas-Magaña",
      "L. Verde",
      "M. Walther",
      "B. A. Weaver",
      "D. H. Weinberg",
      "M. White",
      "M. Wolfson",
      "C. Yèche",
      "J. Yu",
      "E. A. Zaborowski",
      "P. Zarrouk",
      "Z. Zhai",
      "H. Zhang",
      "C. Zhao",
      "G. B. Zhao",
      "R. Zhou",
      "H. Zou"
    ],
    "venue": "",
    "doi": "10.48550/arXiv.2503.14738",
    "url": "http://arxiv.org/abs/2503.14738",
    "summary": "DESI DR2 measures BAO from more than 14 million galaxies and quasars over three survey years and combines them with Lyα BAO. Flat ΛCDM describes the distances but is mildly discrepant with CMB-preferred parameters; evolving dark energy improves DESI+CMB by 3.1σ and by 2.8–4.2σ after adding different supernova samples, while ΛCDM gives Σmν<0.064 eV."
  },
  {
    "key": "A2U26R6Q",
    "title": "DESI DR2 results. I. Baryon acoustic oscillations from the Lyman alpha forest",
    "year": "2025",
    "type": "journalArticle",
    "authors": [
      "M. Abdul Karim",
      "J. Aguilar",
      "S. Ahlen",
      "C. Allende Prieto",
      "O. Alves",
      "A. Anand",
      "U. Andrade",
      "E. Armengaud",
      "A. Aviles",
      "S. Bailey",
      "A. Bault",
      "J. Behera",
      "S. BenZvi",
      "D. Bianchi",
      "C. Blake",
      "A. Brodzeller",
      "D. Brooks",
      "E. Buckley-Geer",
      "E. Burtin",
      "R. Calderon",
      "R. Canning",
      "A. Carnero Rosell",
      "P. Carrilho",
      "L. Casas",
      "F. J. Castander",
      "R. Cereskaite",
      "M. Charles",
      "E. Chaussidon",
      "J. Chaves-Montero",
      "D. Chebat",
      "T. Claybaugh",
      "S. Cole",
      "A. P. Cooper",
      "A. Cuceu",
      "K. S. Dawson",
      "R. de Belsunce",
      "A. de la Macorra",
      "A. de Mattia",
      "N. Deiosso",
      "J. Della Costa",
      "A. Dey",
      "B. Dey",
      "Z. Ding",
      "P. Doel",
      "J. Edelstein",
      "D. J. Eisenstein",
      "W. Elbers",
      "P. Fagrelius",
      "K. Fanning",
      "S. Ferraro",
      "A. Font-Ribera",
      "J. E. Forero-Romero",
      "C. Garcia-Quintero",
      "L. H. Garrison",
      "E. Gaztañaga",
      "H. Gil-Marín",
      "S. Gontcho A Gontcho",
      "A. X. Gonzalez-Morales",
      "C. Gordon",
      "D. Green",
      "G. Gutierrez",
      "J. Guy",
      "C. Hahn",
      "M. Herbold",
      "H. K. Herrera-Alcantar",
      "M. Ho",
      "M.-F. Ho",
      "K. Honscheid",
      "C. Howlett",
      "D. Huterer",
      "M. Ishak",
      "S. Juneau",
      "N. G. Karaçaylı",
      "R. Kehoe",
      "S. Kent",
      "D. Kirkby",
      "T. Kisner",
      "F.-S. Kitaura",
      "S. E. Koposov",
      "A. Kremin",
      "O. Lahav",
      "C. Lamman",
      "M. Landriau",
      "D. Lang",
      "J. Lasker",
      "J. M. Le Goff",
      "L. Le Guillou",
      "A. Leauthaud",
      "M. E. Levi",
      "Q. Li",
      "T. S. Li",
      "K. Lodha",
      "M. Lokken",
      "C. Magneville",
      "M. Manera",
      "P. Martini",
      "W. L. Matthewson",
      "P. McDonald",
      "A. Meisner",
      "J. Mena-Fernández",
      "R. Miquel",
      "J. Moustakas",
      "A. Muñoz-Gutiérrez",
      "D. Muñoz-Santos",
      "A. D. Myers",
      "J. A. Newman",
      "G. Niz",
      "H. E. Noriega",
      "E. Paillas",
      "N. Palanque-Delabrouille",
      "J. Pan",
      "W. J. Percival",
      "I. Pérez-Ràfols",
      "M. M. Pieri",
      "C. Poppett",
      "F. Prada",
      "D. Rabinowitz",
      "A. Raichoor",
      "C. Ramírez-Pérez",
      "M. Rashkovetskyi",
      "C. Ravoux",
      "J. Rich",
      "C. Rockosi",
      "A. J. Ross",
      "G. Rossi",
      "V. Ruhlmann-Kleider",
      "E. Sanchez",
      "N. Sanders",
      "S. Satyavolu",
      "D. Schlegel",
      "M. Schubnell",
      "H. Seo",
      "A. Shafieloo",
      "R. Sharples",
      "J. Silber",
      "F. Sinigaglia",
      "D. Sprayberry",
      "T. Tan",
      "G. Tarlé",
      "P. Taylor",
      "W. Turner",
      "F. Valdes",
      "M. Vargas-Magaña",
      "M. Walther",
      "B. A. Weaver",
      "M. Wolfson",
      "C. Yèche",
      "P. Zarrouk",
      "R. Zhou",
      "H. Zou",
      "DESI Collaboration"
    ],
    "venue": "Physical Review D",
    "doi": "10.1103/2wwn-xjm5",
    "url": "https://ui.adsabs.harvard.edu/abs/2025PhRvD.112h3514A",
    "summary": "Using forests in over 820,000 quasar spectra and positions of more than 1.2 million quasars, DESI DR2 measures radial and transverse BAO at z=2.33 to 1.1% and 1.3%, or 0.65% isotropically. Improved extraction, mocks, and DLA handling support the result, which for the first time includes an explicit theoretical systematic for nonlinear BAO shifts."
  },
  {
    "key": "MXDJRZE9",
    "title": "ForestFlow: predicting the Lyman- α forest clustering from linear to nonlinear scales",
    "year": "2025",
    "type": "journalArticle",
    "authors": [
      "J. Chaves-Montero",
      "L. Cabayol-Garcia",
      "M. Lokken",
      "A. Font-Ribera",
      "J. Aguilar",
      "S. Ahlen",
      "D. Bianchi",
      "D. Brooks",
      "T. Claybaugh",
      "S. Cole",
      "A. De La Macorra",
      "S. Ferraro",
      "J. E. Forero-Romero",
      "E. Gaztañaga",
      "S. Gontcho A Gontcho",
      "G. Gutierrez",
      "K. Honscheid",
      "R. Kehoe",
      "D. Kirkby",
      "A. Kremin",
      "A. Lambert",
      "M. Landriau",
      "M. Manera",
      "P. Martini",
      "R. Miquel",
      "A. Muñoz-Gutiérrez",
      "G. Niz",
      "I. Pérez-Ràfols",
      "G. Rossi",
      "E. Sanchez",
      "M. Schubnell",
      "D. Sprayberry",
      "G. Tarlé",
      "B. A. Weaver"
    ],
    "venue": "Astronomy & Astrophysics",
    "doi": "10.1051/0004-6361/202452039",
    "url": "https://www.aanda.org/10.1051/0004-6361/202452039",
    "summary": "ForestFlow uses conditional normalizing flows to predict Lyα large-scale biases and six nonlinear-correction parameters from cosmology and IGM physics, then combines them with a Boltzmann solver. Trained on 30 paired hydrodynamical simulations, it reproduces three-dimensional flux power to about 3% and one-dimensional power to 1.5% from linear scales to k=5 Mpc^-1, while generalizing to unseen ionization histories, neutrinos, and curvature."
  },
  {
    "key": "2DGSPW2Y",
    "title": "Measuring and predicting galaxy assembly bias across galaxy samples",
    "year": "2025",
    "type": "preprint",
    "authors": [
      "Sergio García-Moreno",
      "Jonás Chaves-Montero"
    ],
    "venue": "",
    "doi": "10.48550/arXiv.2504.06770",
    "url": "http://arxiv.org/abs/2504.06770",
    "summary": "Using IllustrisTNG galaxy samples selected by mass, luminosity, and colour, the paper finds assembly bias can alter clustering by up to 25% and depends strongly on selection, density, and redshift. No single secondary halo property reproduces all samples; an analytic expression instead decomposes the signal into halo assembly bias and occupancy variation for any chosen property."
  },
  {
    "key": "HEXCGBJR",
    "title": "Validation of the DESI DR2 Ly$α$ BAO analysis using synthetic datasets",
    "year": "2025",
    "type": "preprint",
    "authors": [
      "L. Casas",
      "H. K. Herrera-Alcantar",
      "J. Chaves-Montero",
      "A. Cuceu",
      "A. Font-Ribera",
      "M. Lokken",
      "M. Abdul Karim",
      "C. Ramírez-Pérez",
      "J. Aguilar",
      "S. Ahlen",
      "U. Andrade",
      "E. Armengaud",
      "A. Aviles",
      "S. Bailey",
      "S. BenZvi",
      "D. Bianchi",
      "A. Brodzeller",
      "D. Brooks",
      "R. Canning",
      "A. Carnero Rosell",
      "M. Charles",
      "E. Chaussidon",
      "T. Claybaugh",
      "K. S. Dawson",
      "A. de la Macorra",
      "A. de Mattia",
      "Arjun Dey",
      "Biprateep Dey",
      "Z. Ding",
      "P. Doel",
      "D. J. Eisenstein",
      "W. Elbers",
      "S. Ferraro",
      "J. E. Forero-Romero",
      "C. Garcia-Quintero",
      "Lehman H. Garrison",
      "E. Gaztañaga",
      "H. Gil-Marín",
      "S. Gontcho A. Gontcho",
      "A. X. Gonzalez-Morales",
      "C. Gordon",
      "G. Gutierrez",
      "J. Guy",
      "M. Herbold",
      "K. Honscheid",
      "C. Howlett",
      "D. Huterer",
      "M. Ishak",
      "S. Juneau",
      "R. Kehoe",
      "D. Kirkby",
      "T. Kisner",
      "A. Kremin",
      "O. Lahav",
      "M. Landriau",
      "J. M. Le Goff",
      "L. Le Guillou",
      "A. Leauthaud",
      "M. E. Levi",
      "Q. Li",
      "M. Manera",
      "P. Martini",
      "A. Meisner",
      "J. Mena-Fernández",
      "R. Miquel",
      "J. Moustakas",
      "D. Muñoz Santos",
      "A. D. Myers",
      "S. Nadathur",
      "L. Napolitano",
      "G. Niz",
      "H. E. Noriega",
      "E. Paillas",
      "N. Palanque-Delabrouille",
      "W. J. Percival",
      "Matthew M. Pieri",
      "C. Poppett",
      "F. Prada",
      "I. Pérez-Ràfols",
      "C. Ravoux",
      "G. Rossi",
      "E. Sanchez",
      "D. Schlegel",
      "M. Schubnell",
      "H. Seo",
      "F. Sinigaglia",
      "D. Sprayberry",
      "T. Tan",
      "G. Tarlé",
      "P. Taylor",
      "W. Turner",
      "M. Vargas-Magaña",
      "M. Walther",
      "B. A. Weaver",
      "M. Wolfson",
      "C. Yèche",
      "P. Zarrouk",
      "R. Zhou"
    ],
    "venue": "",
    "doi": "10.48550/arXiv.2503.14741",
    "url": "http://arxiv.org/abs/2503.14741",
    "summary": "This paper validates the DR2 Lyα BAO pipeline with 400 mock realizations, including new CoLoRe-QL simulations that reproduce nonlinear BAO broadening. It also studies quasar-redshift errors and alternative damped-absorber masking choices, substantially extending the mock realism and statistical power beyond the DR1 validation."
  },
  {
    "key": "3VE89LGJ",
    "title": "DESI 2024 IV: Baryon Acoustic Oscillations from the Lyman Alpha Forest",
    "year": "2024",
    "type": "preprint",
    "authors": [
      "DESI Collaboration",
      "A. G. Adame",
      "J. Aguilar",
      "S. Ahlen",
      "S. Alam",
      "D. M. Alexander",
      "M. Alvarez",
      "O. Alves",
      "A. Anand",
      "U. Andrade",
      "E. Armengaud",
      "S. Avila",
      "A. Aviles",
      "H. Awan",
      "S. Bailey",
      "C. Baltay",
      "A. Bault",
      "J. Bautista",
      "J. Behera",
      "S. BenZvi",
      "F. Beutler",
      "D. Bianchi",
      "C. Blake",
      "R. Blum",
      "S. Brieden",
      "A. Brodzeller",
      "D. Brooks",
      "E. Buckley-Geer",
      "E. Burtin",
      "R. Calderon",
      "R. Canning",
      "A. Carnero Rosell",
      "R. Cereskaite",
      "J. L. Cervantes-Cota",
      "S. Chabanier",
      "E. Chaussidon",
      "J. Chaves-Montero",
      "S. Chen",
      "X. Chen",
      "T. Claybaugh",
      "S. Cole",
      "A. Cuceu",
      "T. M. Davis",
      "K. Dawson",
      "R. de la Cruz",
      "A. de la Macorra",
      "A. de Mattia",
      "N. Deiosso",
      "A. Dey",
      "B. Dey",
      "J. Ding",
      "Z. Ding",
      "P. Doel",
      "J. Edelstein",
      "S. Eftekharzadeh",
      "D. J. Eisenstein",
      "A. Elliott",
      "P. Fagrelius",
      "K. Fanning",
      "S. Ferraro",
      "J. Ereza",
      "N. Findlay",
      "B. Flaugher",
      "A. Font-Ribera",
      "D. Forero-Sánchez",
      "J. E. Forero-Romero",
      "C. Garcia-Quintero",
      "E. Gaztañaga",
      "H. Gil-Marín",
      "S. Gontcho A Gontcho",
      "A. X. Gonzalez-Morales",
      "V. Gonzalez-Perez",
      "C. Gordon",
      "D. Green",
      "D. Gruen",
      "R. Gsponer",
      "G. Gutierrez",
      "J. Guy",
      "B. Hadzhiyska",
      "C. Hahn",
      "M. M. S Hanif",
      "H. K. Herrera-Alcantar",
      "K. Honscheid",
      "C. Howlett",
      "D. Huterer",
      "V. Iršič",
      "M. Ishak",
      "S. Juneau",
      "N. G. Karaçayli",
      "R. Kehoe",
      "S. Kent",
      "D. Kirkby",
      "A. Kremin",
      "A. Krolewski",
      "Y. Lai",
      "T. -W. Lan",
      "M. Landriau",
      "D. Lang",
      "J. Lasker",
      "J. M. Le Goff",
      "L. Le Guillou",
      "A. Leauthaud",
      "M. E. Levi",
      "T. S. Li",
      "E. Linder",
      "K. Lodha",
      "C. Magneville",
      "M. Manera",
      "D. Margala",
      "P. Martini",
      "M. Maus",
      "P. McDonald",
      "L. Medina-Varela",
      "A. Meisner",
      "J. Mena-Fernández",
      "R. Miquel",
      "J. Moon",
      "S. Moore",
      "J. Moustakas",
      "N. Mudur",
      "E. Mueller",
      "A. Muñoz-Gutiérrez",
      "A. D. Myers",
      "S. Nadathur",
      "L. Napolitano",
      "R. Neveux",
      "J. A. Newman",
      "N. M. Nguyen",
      "J. Nie",
      "G. Niz",
      "H. E. Noriega",
      "N. Padmanabhan",
      "E. Paillas",
      "N. Palanque-Delabrouille",
      "J. Pan",
      "S. Penmetsa",
      "W. J. Percival",
      "M. M. Pieri",
      "M. Pinon",
      "C. Poppett",
      "A. Porredon",
      "F. Prada",
      "A. Pérez-Fernández",
      "I. Pérez-Ràfols",
      "D. Rabinowitz",
      "A. Raichoor",
      "C. Ramírez-Pérez",
      "S. Ramirez-Solano",
      "M. Rashkovetskyi",
      "C. Ravoux",
      "M. Rezaie",
      "J. Rich",
      "A. Rocher",
      "C. Rockosi",
      "N. A. Roe",
      "A. Rosado-Marin",
      "A. J. Ross",
      "G. Rossi",
      "R. Ruggeri",
      "V. Ruhlmann-Kleider",
      "L. Samushia",
      "E. Sanchez",
      "C. Saulder",
      "E. F. Schlafly",
      "D. Schlegel",
      "M. Schubnell",
      "H. Seo",
      "R. Sharples",
      "J. Silber",
      "F. Sinigaglia",
      "A. Slosar",
      "A. Smith",
      "D. Sprayberry",
      "T. Tan",
      "G. Tarlé",
      "S. Trusov",
      "R. Vaisakh",
      "D. Valcin",
      "F. Valdes",
      "M. Vargas-Magaña",
      "L. Verde",
      "M. Walther",
      "B. Wang",
      "M. S. Wang",
      "B. A. Weaver",
      "N. Weaverdyck",
      "R. H. Wechsler",
      "D. H. Weinberg",
      "M. White",
      "J. Yu",
      "Y. Yu",
      "S. Yuan",
      "C. Yèche",
      "E. A. Zaborowski",
      "P. Zarrouk",
      "H. Zhang",
      "C. Zhao",
      "R. Zhao",
      "R. Zhou",
      "H. Zou"
    ],
    "venue": "",
    "doi": "10.48550/arXiv.2404.03001",
    "url": "https://ui.adsabs.harvard.edu/abs/2024arXiv240403001D",
    "summary": "The first-year DESI Lyα BAO analysis uses more than 420,000 forest spectra and over 700,000 quasars, with blinded methods validated on synthetic data and data splits. At z=2.33 it measures the Hubble rate to 2% and transverse comoving distance to 2.4%, providing a robust high-redshift expansion anchor."
  },
  {
    "key": "DEJ9HS6D",
    "title": "DESI 2024 VI: Cosmological Constraints from the Measurements of Baryon Acoustic Oscillations",
    "year": "2024",
    "type": "preprint",
    "authors": [
      "DESI Collaboration",
      "A. G. Adame",
      "J. Aguilar",
      "S. Ahlen",
      "S. Alam",
      "D. M. Alexander",
      "M. Alvarez",
      "O. Alves",
      "A. Anand",
      "U. Andrade",
      "E. Armengaud",
      "S. Avila",
      "A. Aviles",
      "H. Awan",
      "B. Bahr-Kalus",
      "S. Bailey",
      "C. Baltay",
      "A. Bault",
      "J. Behera",
      "S. BenZvi",
      "A. Bera",
      "F. Beutler",
      "D. Bianchi",
      "C. Blake",
      "R. Blum",
      "S. Brieden",
      "A. Brodzeller",
      "D. Brooks",
      "E. Buckley-Geer",
      "E. Burtin",
      "R. Calderon",
      "R. Canning",
      "A. Carnero Rosell",
      "R. Cereskaite",
      "J. L. Cervantes-Cota",
      "S. Chabanier",
      "E. Chaussidon",
      "J. Chaves-Montero",
      "S. Chen",
      "X. Chen",
      "T. Claybaugh",
      "S. Cole",
      "A. Cuceu",
      "T. M. Davis",
      "K. Dawson",
      "A. de la Macorra",
      "A. de Mattia",
      "N. Deiosso",
      "A. Dey",
      "B. Dey",
      "Z. Ding",
      "P. Doel",
      "J. Edelstein",
      "S. Eftekharzadeh",
      "D. J. Eisenstein",
      "A. Elliott",
      "P. Fagrelius",
      "K. Fanning",
      "S. Ferraro",
      "J. Ereza",
      "N. Findlay",
      "B. Flaugher",
      "A. Font-Ribera",
      "D. Forero-Sánchez",
      "J. E. Forero-Romero",
      "C. S. Frenk",
      "C. Garcia-Quintero",
      "E. Gaztañaga",
      "H. Gil-Marín",
      "S. Gontcho A. Gontcho",
      "A. X. Gonzalez-Morales",
      "V. Gonzalez-Perez",
      "C. Gordon",
      "D. Green",
      "D. Gruen",
      "R. Gsponer",
      "G. Gutierrez",
      "J. Guy",
      "B. Hadzhiyska",
      "C. Hahn",
      "M. M. S. Hanif",
      "H. K. Herrera-Alcantar",
      "K. Honscheid",
      "C. Howlett",
      "D. Huterer",
      "V. Iršič",
      "M. Ishak",
      "S. Juneau",
      "N. G. Karaçaylı",
      "R. Kehoe",
      "S. Kent",
      "D. Kirkby",
      "A. Kremin",
      "A. Krolewski",
      "Y. Lai",
      "T.-W. Lan",
      "M. Landriau",
      "D. Lang",
      "J. Lasker",
      "J. M. Le Goff",
      "L. Le Guillou",
      "A. Leauthaud",
      "M. E. Levi",
      "T. S. Li",
      "E. Linder",
      "K. Lodha",
      "C. Magneville",
      "M. Manera",
      "D. Margala",
      "P. Martini",
      "M. Maus",
      "P. McDonald",
      "L. Medina-Varela",
      "A. Meisner",
      "J. Mena-Fernández",
      "R. Miquel",
      "J. Moon",
      "S. Moore",
      "J. Moustakas",
      "N. Mudur",
      "E. Mueller",
      "A. Muñoz-Gutiérrez",
      "A. D. Myers",
      "S. Nadathur",
      "L. Napolitano",
      "R. Neveux",
      "J. A. Newman",
      "N. M. Nguyen",
      "J. Nie",
      "G. Niz",
      "H. E. Noriega",
      "N. Padmanabhan",
      "E. Paillas",
      "N. Palanque-Delabrouille",
      "J. Pan",
      "S. Penmetsa",
      "W. J. Percival",
      "M. Pieri",
      "M. Pinon",
      "C. Poppett",
      "A. Porredon",
      "F. Prada",
      "A. Pérez-Fernández",
      "I. Pérez-Ràfols",
      "D. Rabinowitz",
      "A. Raichoor",
      "C. Ramírez-Pérez",
      "S. Ramirez-Solano",
      "M. Rashkovetskyi",
      "M. Rezaie",
      "J. Rich",
      "A. Rocher",
      "C. Rockosi",
      "N. A. Roe",
      "A. Rosado-Marin",
      "A. J. Ross",
      "G. Rossi",
      "R. Ruggeri",
      "V. Ruhlmann-Kleider",
      "L. Samushia",
      "E. Sanchez",
      "C. Saulder",
      "E. F. Schlafly",
      "D. Schlegel",
      "M. Schubnell",
      "H. Seo",
      "A. Shafieloo",
      "R. Sharples",
      "J. Silber",
      "A. Slosar",
      "A. Smith",
      "D. Sprayberry",
      "T. Tan",
      "G. Tarlé",
      "P. Taylor",
      "S. Trusov",
      "L. A. Ureña-López",
      "R. Vaisakh",
      "D. Valcin",
      "F. Valdes",
      "M. Vargas-Magaña",
      "L. Verde",
      "M. Walther",
      "B. Wang",
      "M. S. Wang",
      "B. A. Weaver",
      "N. Weaverdyck",
      "R. H. Wechsler",
      "D. H. Weinberg",
      "M. White",
      "J. Yu",
      "Y. Yu",
      "S. Yuan",
      "C. Yèche",
      "E. A. Zaborowski",
      "P. Zarrouk",
      "H. Zhang",
      "C. Zhao",
      "R. Zhao",
      "R. Zhou",
      "T. Zhuang",
      "H. Zou"
    ],
    "venue": "",
    "doi": "",
    "url": "http://arxiv.org/abs/2404.03002",
    "summary": "Using more than six million DESI DR1 galaxies, quasars, and Lyα forests, this analysis measures BAO distances in seven bins over 0.1<z<4.2. Flat ΛCDM fits well, with DESI+CMB giving H0≈67.97 km/s/Mpc, while combinations with supernovae show a data-set-dependent 2.5–3.9σ preference for evolving dark energy and impose strong neutrino-mass limits."
  },
  {
    "key": "BFQEUMF9",
    "title": "Investigating the galaxy-halo connection of DESI Emission-Line Galaxies with SHAMe-SF",
    "year": "2024",
    "type": "preprint",
    "authors": [
      "Sara Ortega-Martinez",
      "Sergio Contreras",
      "Raul E. Angulo",
      "Jonas Chaves-Montero"
    ],
    "venue": "",
    "doi": "10.48550/arXiv.2411.11830",
    "url": "http://arxiv.org/abs/2411.11830",
    "summary": "SHAMe-SF extends abundance matching with star formation, stripping, environment, and quenching and fits DESI One-Percent ELG clustering from 0.1 to 30 h^-1 Mpc. Validation on TNG300 and L-Galaxies mocks supports the inference that central and satellite ELGs occupy haloes near 10^11.8 and 10^12.5 h^-1 solar masses, with a satellite fraction around 30% and evidence for assembly bias and conformity."
  },
  {
    "key": "KR7ANYG2",
    "title": "The J-PLUS collaboration. Additive versus multiplicative systematics in surveys of the large scale structure of the Universe",
    "year": "2024",
    "type": "preprint",
    "authors": [
      "C. Hernández-Monteagudo",
      "G. Aricò",
      "J. Chaves-Montero",
      "L. R. Abramo",
      "P. Arnalte-Mur",
      "A. Hernán-Caballero",
      "C. López-Sanjuan",
      "V. Marra",
      "R. von Marttens",
      "E. Tempel",
      "J. Cenarro",
      "D. Cristóbal-Hornillos",
      "A. Marín-Franch",
      "M. Moles",
      "J. Varela",
      "H. Vázquez Ramió",
      "J. Alcaniz",
      "R. Dupke",
      "A. Ederoclite",
      "L. Sodré Jr",
      "R. E. Angulo"
    ],
    "venue": "",
    "doi": "10.48550/arXiv.2412.14827",
    "url": "http://arxiv.org/abs/2412.14827",
    "summary": "The paper develops a hybrid contamination model and correction algorithm in which multiple survey systematics may affect observed tracer densities additively, multiplicatively, or both. Tests on J-PLUS-inspired mocks show that it outperforms methods imposing a single contamination type when the true effects are mixed, while remaining competitive in simpler cases."
  },
  {
    "key": "FN6ATCXH",
    "title": "Validating the clustering predictions of empirical models with the FLAMINGO simulations",
    "year": "2024",
    "type": "preprint",
    "authors": [
      "Sergio Contreras",
      "Raul E. Angulo",
      "Jonás Chaves-Montero",
      "Roi Kugel",
      "Matthieu Schaller",
      "Joop Schaye"
    ],
    "venue": "",
    "doi": "",
    "url": "https://ui.adsabs.harvard.edu/abs/2024arXiv240718912C",
    "summary": "The paper builds GalaxyEmu-Planck to compare a 13-parameter HOD and SHAMe against FLAMINGO galaxy samples using clustering, lensing, and higher-order statistics. Both models fit two-point probes, but SHAMe better reproduces higher-order signals and galaxy assembly bias with fewer parameters; two HOD parameters prove unnecessary."
  },
  {
    "key": "S3UN25I5",
    "title": "3D correlations in the Lyman-α forest from early DESI data",
    "year": "2023",
    "type": "journalArticle",
    "authors": [
      "C. Gordon",
      "A. Cuceu",
      "J. Chaves-Montero",
      "A. Font-Ribera",
      "A. X. González-Morales",
      "J. Aguilar",
      "S. Ahlen",
      "E. Armengaud",
      "S. Bailey",
      "A. Bault",
      "A. Brodzeller",
      "D. Brooks",
      "T. Claybaugh",
      "R. de la Cruz",
      "K. Dawson",
      "P. Doel",
      "J. E. Forero-Romero",
      "S. Gontcho A. Gontcho",
      "J. Guy",
      "H. K. Herrera-Alcantar",
      "V. Iršič",
      "N. G. Karaçaylı",
      "D. Kirkby",
      "M. Landriau",
      "L. Le Guillou",
      "M. E. Levi",
      "A. de la Macorra",
      "M. Manera",
      "P. Martini",
      "A. Meisner",
      "R. Miquel",
      "P. Montero-Camacho",
      "A. Muñoz-Gutiérrez",
      "L. Napolitano",
      "J. Nie",
      "G. Niz",
      "N. Palanque-Delabrouille",
      "W. J. Percival",
      "M. Pieri",
      "C. Poppett",
      "F. Prada",
      "I. Pérez-Ràfols",
      "C. Ramírez-Pérez",
      "C. Ravoux",
      "M. Rezaie",
      "A. J. Ross",
      "G. Rossi",
      "E. Sanchez",
      "D. Schlegel",
      "M. Schubnell",
      "H. Seo",
      "F. Sinigaglia",
      "T. Tan",
      "G. Tarlé",
      "M. Walther",
      "B. A. Weaver",
      "C. Yèche",
      "Z. Zhou",
      "H. Zou"
    ],
    "venue": "Journal of Cosmology and Astroparticle Physics",
    "doi": "10.1088/1475-7516/2023/11/045",
    "url": "https://ui.adsabs.harvard.edu/abs/2023JCAP...11..045G",
    "summary": "The first DESI Lyα three-dimensional analysis measures forest auto-correlation from 88,509 high-redshift quasars and forest–quasar cross-correlation using 147,899 tracers. A 13-parameter linear model fits well, detects the BAO peak at 3.8σ, and agrees with eBOSS despite using only a small fraction of the eventual DESI sample."
  },
  {
    "key": "4YWA9RQD",
    "title": "A neural network emulator for the Lyman-α forest 1D flux power spectrum",
    "year": "2023",
    "type": "journalArticle",
    "authors": [
      "L Cabayol-Garcia",
      "J Chaves-Montero",
      "A Font-Ribera",
      "C Pedersen"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnras/stad2512",
    "url": "https://academic.oup.com/mnras/article/525/3/3499/7246913",
    "summary": "This paper emulates the Lyα one-dimensional flux power as a function of the amplitude and slope of the linear matter spectrum plus IGM parameters, rather than specific cosmological parameters. The neural network reaches sub-percent accuracy over z=2–4.5 and relevant scales and generalizes at roughly percent level to massive neutrinos, running, curvature, and unseen thermal or ionization histories."
  },
  {
    "key": "KAVB3DXR",
    "title": "Active galactic nuclei, gravitational redshifts, and cosmological tensions",
    "year": "2023",
    "type": "preprint",
    "authors": [
      "S. Carneiro",
      "N. D. Padilla",
      "J. Chaves-Montero",
      "C. J. Donzelli",
      "C. Pigozzo",
      "P. Colazo",
      "J. S. Alcaniz"
    ],
    "venue": "",
    "doi": "10.48550/arXiv.2304.13036",
    "url": "http://arxiv.org/abs/2304.13036",
    "summary": "The paper estimates gravitational redshifts in AGN emission lines using Seyfert, SDSS-quasar, and SAMI LINER samples, finding characteristic shifts of order 10^-4 consistent with billion-solar-mass black holes and parsec-scale broad-line regions. Non-AGN galaxies show shifts consistent with zero, so the effect is negligible for cosmological inference from typical Type-Ia-supernova hosts."
  },
  {
    "key": "N8S98KCG",
    "title": "Consistent and simultaneous modelling of galaxy clustering and galaxy-galaxy lensing with subhalo abundance matching",
    "year": "2023",
    "type": "journalArticle",
    "authors": [
      "Sergio Contreras",
      "Raul E. Angulo",
      "Jonás Chaves-Montero",
      "Simon D. M. White",
      "Giovanni Aricò"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnras/stad122",
    "url": "https://ui.adsabs.harvard.edu/abs/2023MNRAS.520..489C",
    "summary": "The spatial distribution of galaxies and their gravitational lensing signal offer complementary tests of galaxy formation physics and cosmology. However, their synergy can only be fully exploited if both probes are modelled accurately and consistently. In this paper, we demonstrate that this can be achieved using an extension of Sub-Halo Abundance Matching extended model (SHAMe), dubbed SHAMe. Specifically, we use mock catalogues built from the TNG300 hydrodynamical simulation to show that SHAMe can simultaneously model the multipoles of the redshift-space galaxy correlation function and galaxy-galaxy lensing, without noticeable bias within the statistical sampling uncertainties of a SDSS volume and on scales r ∈ [0.6 - 30]h-1 Mpc. Modelling the baryonic processes in galaxy-galaxy lensing with a baryonification scheme allows SHAMe's range of validity to be extended to r ∈ [0.1 - 30] h-1 Mpc. Remarkably, our model achieves this level of precision with just five free parameters beyond those describing the baryonification model. At fixed cosmology, we find that galaxy-galaxy lensing provides a general consistency test but little additional information on galaxy modelling parameters beyond that encoded in the redshift-space multipoles. It does, however, improve constraints if only the projected correlation function is available, as in surveys with only photometric redshifts. We expect SHAMe to have a higher fidelity across a wider range of scales than more traditional methods such as Halo Occupation Distribution modelling. Thus it should provide a significantly more powerful and more robust tool for analysing next-generation large-scale surveys."
  },
  {
    "key": "N8JMBQN5",
    "title": "Consistent clustering and lensing of SDSS-III BOSS galaxies with an extended abundance matching formalism",
    "year": "2023",
    "type": "journalArticle",
    "authors": [
      "Sergio Contreras",
      "Jonás Chaves-Montero",
      "Raul E Angulo"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnras/stad2434",
    "url": "https://doi.org/10.1093/mnras/stad2434",
    "summary": "The paper applies SHAMe to TNG300-like mocks and to BOSS clustering and galaxy–galaxy lensing at z=0.31–0.43. It fits both observables in Planck and low-S8 cosmologies, showing that the lensing-is-low discrepancy can arise from restrictive galaxy–halo models rather than a failure of ΛCDM; inferred assembly bias differs between the two cosmologies."
  },
  {
    "key": "Q6EZKJDK",
    "title": "Diffstar: a fully parametric physical model for galaxy assembly history",
    "year": "2023",
    "type": "journalArticle",
    "authors": [
      "Alex Alarcon",
      "Andrew P. Hearin",
      "Matthew R. Becker",
      "Jonás Chaves-Montero"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnras/stac3118",
    "url": "https://ui.adsabs.harvard.edu/abs/2023MNRAS.518..562A",
    "summary": "Diffstar is a smooth, differentiable model of in-situ star formation built from halo growth, gas accretion, star-formation efficiency, gas-consumption time, quenching, and possible rejuvenation. It fits average stellar-mass histories in IllustrisTNG and UniverseMachine to about 0.1 dex and reveals systematic differences: UniverseMachine is less efficient and burstier, has longer consumption times, and predicts more rejuvenation."
  },
  {
    "key": "F94SPEIY",
    "title": "DSPS: Differentiable stellar population synthesis",
    "year": "2023",
    "type": "journalArticle",
    "authors": [
      "Andrew P. Hearin",
      "Jonás Chaves-Montero",
      "Alex Alarcon",
      "Matthew R. Becker",
      "Andrew Benson"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnras/stad456",
    "url": "https://ui.adsabs.harvard.edu/abs/2023MNRAS.521.1741H",
    "summary": "DSPS implements stellar-population synthesis natively in JAX, making galaxy spectra and photometry differentiable with respect to star-formation history, metallicity, nebular emission, and dust. It adds age-correlated metallicity and Diffstar integration and reports speedups of about five on CPUs and 300–400 on GPUs for population forward modelling."
  },
  {
    "key": "UBPAA3QB",
    "title": "The galaxy formation origin of the lensing is low problem",
    "year": "2023",
    "type": "journalArticle",
    "authors": [
      "Jonás Chaves-Montero",
      "Raul E. Angulo",
      "Sergio Contreras"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnras/stad243",
    "url": "https://ui.adsabs.harvard.edu/abs/2023MNRAS.521..937C",
    "summary": "Recent analyses show that ΛCDM-based models optimized to reproduce the clustering of massive galaxies overestimate their gravitational lensing by about 30 per cent, the so-called lensing is low problem. Using a state-of-the-art hydrodynamical simulation, we show that this discrepancy reflects shortcomings in standard galaxy-halo connection models rather than tensions within the ΛCDM paradigm itself. Specifically, this problem results from ignoring a variety of galaxy formation effects, including assembly bias, segregation of satellite galaxies relative to dark matter, and baryonic effects on the matter distribution. All these effects contribute towards overestimating gravitational lensing, and when combined, explain the amplitude and scale dependence of the lensing is low problem. We conclude that simplistic galaxy-halo connection models are inadequate to interpret clustering and lensing simultaneously, and that it is crucial to employ more sophisticated models for the upcoming generation of large-scale surveys."
  },
  {
    "key": "BQT49DZ2",
    "title": "A nearly complete census of intergalactic gas using the kinematic Sunyaev-Zel?dovich effect",
    "year": "2022",
    "type": "bookSection",
    "authors": [
      "Jonés Chaves-Montero"
    ],
    "venue": "The Sixteenth Marcel Grossmann Meeting",
    "doi": "",
    "url": "https://www.worldscientific.com/doi/10.1142/9789811269776_0182",
    "summary": "This conference contribution summarizes ARF–kSZ tomography, which cross-correlates angular-redshift-fluctuation maps with aperture-filtered CMB maps. An 11σ detection using 6dF, BOSS, and SDSS quasars from z=0 to 5 indicates that much of the signal arises outside haloes from gas at roughly 10–250 times the cosmic mean density, accounting for about half of all baryons."
  },
  {
    "key": "WVPMH8WI",
    "title": "Black hole virial masses from single-epoch photometry: The miniJPAS test case",
    "year": "2022",
    "type": "journalArticle",
    "authors": [
      "J. Chaves-Montero",
      "S. Bonoli",
      "B. Trakhtenbrot",
      "A. Fernández-Centeno",
      "C. Queiroz",
      "L. A. Díaz-García",
      "R. M. González Delgado",
      "A. Hernán-Caballero",
      "C. Hernández-Monteagudo",
      "C. Lópen-Sanjuan",
      "R. Overzier",
      "D. Sobral",
      "L. R. Abramo",
      "J. Alcaniz",
      "N. Benitez",
      "S. Carneiro",
      "A. J. Cenarro",
      "D. Cristóbal-Hornillos",
      "R. A. Dupke",
      "A. Ederoclite",
      "A. Marín-Franch",
      "C. Mendes de Oliveira",
      "M. Moles",
      "L. Sodré",
      "K. Taylor",
      "J. Varela",
      "H. Vázquez Ramió",
      "T. Civera"
    ],
    "venue": "Astronomy & Astrophysics",
    "doi": "10.1051/0004-6361/202142567",
    "url": "https://www.aanda.org/10.1051/0004-6361/202142567",
    "summary": "The paper introduces a forward-modelling method that infers broad-emission-line widths and virial black-hole masses from narrow-band photometry. For SDSS quasars observed by miniJPAS, the photometric masses show no systematic offset from spectroscopic single-epoch estimates, with scatter decreasing from about 0.4 dex at log MBH=8 to 0.07 dex at log MBH=9.75."
  },
  {
    "key": "GNMN8XV3",
    "title": "Machine learning synthetic spectra for probabilistic redshift estimation: SYTH-Z",
    "year": "2022",
    "type": "journalArticle",
    "authors": [
      "Nesar Ramachandra",
      "Jonás Chaves-Montero",
      "Alex Alarcon",
      "Arindam Fadikar",
      "Salman Habib",
      "Katrin Heitmann"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnras/stac1790",
    "url": "https://academic.oup.com/mnras/article/515/2/1927/6623680",
    "summary": "SYTH-Z trains a mixture-density network on physically motivated synthetic spectral energy distributions matched to the target survey’s colour–redshift space. A zero-point recalibration reduces synthetic-to-observed offsets, and the resulting probabilistic photo-z estimates outperform baselines trained only on incomplete and biased observational spectroscopy across a broad redshift range."
  },
  {
    "key": "2RS6R7SE",
    "title": "Relativistic Angular Redshift Fluctuations embedded in Large Scale Varying Gravitational Potentials",
    "year": "2022",
    "type": "report",
    "authors": [
      "Adal Lima-Hernández",
      "Carlos Hernández-Monteagudo",
      "Jonás Chaves-Montero"
    ],
    "venue": "",
    "doi": "",
    "url": "https://ui.adsabs.harvard.edu/abs/2022arXiv220315008L",
    "summary": "This paper derives the linear general-relativistic contributions to angular redshift fluctuations and implements them in a Boltzmann calculation. Peculiar-velocity terms dominate on large scales, lensing matters for wide shells and small angles, and direct potential terms are tiny; ARF also correlate strongly with CMB lensing and show a predicted 4–5σ anti-correlation with the integrated Sachs–Wolfe signal near z≈2."
  },
  {
    "key": "2Y3LP58K",
    "title": "The cosmology dependence of the concentration-mass-redshift relation",
    "year": "2022",
    "type": "preprint",
    "authors": [
      "Daniel López-Cano",
      "Raúl E. Angulo",
      "Aaron D. Ludlow",
      "M. Zennaro",
      "S. Contreras",
      "Jonás Chaves-Montero",
      "G. Aricò"
    ],
    "venue": "",
    "doi": "10.48550/arXiv.2207.13718",
    "url": "http://arxiv.org/abs/2207.13718",
    "summary": "Using 72 gravity-only simulations varying eight cosmological parameters, the paper maps how relaxed-halo concentration changes with mass, redshift, and cosmology. It confirms a tight link between density within the scale radius and cosmic density at a suitably defined formation time, uses excursion-set assembly histories to build an accurate predictive model, and benchmarks where existing concentration prescriptions succeed or fail."
  },
  {
    "key": "FMJMQM45",
    "title": "Tracking the evolution of satellite galaxies: mass stripping and dark-matter deficient galaxies",
    "year": "2022",
    "type": "report",
    "authors": [
      "Antonio D. Montero-Dorta",
      "Facundo Rodriguez",
      "M. Celeste Artale",
      "Rory Smith",
      "Jonas Chaves-Montero"
    ],
    "venue": "",
    "doi": "",
    "url": "https://ui.adsabs.harvard.edu/abs/2022arXiv221212090M",
    "summary": "The paper follows satellites accreted before z=1 through the IllustrisTNG simulations to quantify how tidal evolution depends on host mass and pericentric distance. Close passages can reduce dark-matter mass to a few–20% of its earlier value, affect stellar growth and quenching, and naturally produce dark-matter-deficient galaxies preferentially after very close encounters in massive clusters."
  },
  {
    "key": "7U2XVGND",
    "title": "A Differentiable Model of the Assembly of Individual and Populations of Dark Matter Halos",
    "year": "2021",
    "type": "journalArticle",
    "authors": [
      "Andrew P. Hearin",
      "Jonás Chaves-Montero",
      "Mathew R. Becker",
      "Alex Alarcon"
    ],
    "venue": "The Open Journal of Astrophysics",
    "doi": "10.21105/astro.2105.05859",
    "url": "https://ui.adsabs.harvard.edu/abs/2021OJAp....4E...7H",
    "summary": "This paper presents a three-parameter empirical model for individual dark-matter halo mass-accretion histories, with a smooth transition from early fast growth to late slow growth. Calibrated on high-resolution gravity-only and IllustrisTNG merger trees, it reproduces halo growth to about 0.1 dex after the first gigayear and extends to population-level distributions that capture both mean assembly and diversity. Its JAX implementation also reproduces assembly-bias correlations while leaving negligible environment-correlated residuals."
  },
  {
    "key": "N44K4P9E",
    "title": "Density weighted angular redshift fluctuations: a new cosmological observable",
    "year": "2021",
    "type": "journalArticle",
    "authors": [
      "Carlos Hernández-Monteagudo",
      "Jonás Chaves-Montero",
      "Raúl E. Angulo"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnrasl/slaa172",
    "url": "https://ui.adsabs.harvard.edu/abs/2021MNRAS.503L..56H",
    "summary": "The paper introduces density-weighted angular redshift fluctuations, constructed from galaxy redshifts projected through narrow redshift windows. Theory and simulations show sensitivity to both density and peculiar velocity, roughly 60% correlation with projected line-of-sight velocity, little correlation with ordinary angular density for narrow windows, and resilience to redshift-independent number-count systematics; joint forecasts improve growth, bias, and primordial-non-Gaussianity constraints."
  },
  {
    "key": "X3UHHLUQ",
    "title": "Measuring the evolution of intergalactic gas from z = 0 to 5 using the kinematic Sunyaev–Zel’dovich effect",
    "year": "2021",
    "type": "journalArticle",
    "authors": [
      "Jonás Chaves-Montero",
      "Carlos Hernández-Monteagudo",
      "Raúl E Angulo",
      "J D Emberson"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnras/staa3782",
    "url": "https://academic.oup.com/mnras/article/503/2/1798/6184230",
    "summary": "The paper introduces angular-redshift-fluctuation–kSZ tomography, cross-correlating velocity-sensitive angular redshift maps with aperture-filtered CMB maps. Using 6dF galaxies, BOSS galaxies, and SDSS quasars, it reports an 11σ kSZ detection spanning redshifts 0–5. Modelling the aperture and redshift dependence indicates that much of the signal comes from gas outside dark-matter haloes, at overdensities of roughly 10–250, and that this component accounts for about half of the cosmic baryon budget."
  },
  {
    "key": "XWBGT77P",
    "title": "On the influence of halo mass accretion history on galaxy properties and assembly bias",
    "year": "2021",
    "type": "journalArticle",
    "authors": [
      "Antonio D Montero-Dorta",
      "Jonás Chaves-Montero",
      "M Celeste Artale",
      "Ginevra Favole"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnras/stab2556",
    "url": "https://doi.org/10.1093/mnras/stab2556",
    "summary": "Using IllustrisTNG300, the paper relates the slope of a halo’s specific mass-accretion history to its galaxy’s stellar fraction, gas loss, star-formation peak, and quenching. This slope is a more stable predictor than conventional formation time, and the assembly-bias signal of progenitors grows toward high redshift, reaching a factor of two at z=1 for haloes near 10^11.5–10^12 h^-1 solar masses."
  },
  {
    "key": "VPGYCY3R",
    "title": "Scalable statistical inference of photometric redshift via data subsampling",
    "year": "2021",
    "type": "conferencePaper",
    "authors": [
      "Arindam Fadikar",
      "Stefan M. Wild",
      "Jonas Chaves-Montero"
    ],
    "venue": "",
    "doi": "",
    "url": "",
    "summary": "The paper develops a scalable probabilistic regression framework for large, imbalanced data sets and applies it to photometric-redshift inference. It partitions the input space into balanced regions, uses a graph-based strategy to draw informative subsamples, fits an ensemble of Gaussian processes, and combines their predictive distributions. On SDSS data, the approach retains explicit uncertainty estimates while avoiding the computational cost of fitting a single Gaussian process to the full training set."
  },
  {
    "key": "NZKWPVIM",
    "title": "Surrogate modelling the Baryonic Universe II: On forward modelling the colours of individual and populations of galaxies",
    "year": "2021",
    "type": "journalArticle",
    "authors": [
      "Jonás Chaves-Montero",
      "Andrew Hearin"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnras/stab1831",
    "url": "https://ui.adsabs.harvard.edu/abs/2021MNRAS.506.2373C",
    "summary": "Using FSPS together with IllustrisTNG and UniverseMachine histories, this paper quantifies how unresolved star-formation variability propagates into broad-band galaxy colours. It finds that UniverseMachine histories are more bursty, that short-timescale star formation dominates colour uncertainty over metallicity or dust variability, and that individual-galaxy colours require substantially more complex histories than population-level colour distributions."
  },
  {
    "key": "R89CK2V3",
    "title": "The cosmological dependence of halo and galaxy assembly bias",
    "year": "2021",
    "type": "journalArticle",
    "authors": [
      "S. Contreras",
      "J. Chaves-Montero",
      "M. Zennaro",
      "R. E. Angulo"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnras/stab2367",
    "url": "https://ui.adsabs.harvard.edu/abs/2021MNRAS.tmp.2178C",
    "summary": "Using gravity-only simulations spanning standard cosmological parameters, massive neutrinos, and evolving dark energy, the paper tests whether assembly bias changes with cosmology. Halo assembly-bias variations remain below about 0.05 dex, while galaxy assembly bias changes by only roughly 2–4% of the total clustering signal; parameters controlling the galaxy–halo model have a much larger effect."
  },
  {
    "key": "9DVW478Q",
    "title": "The miniJPAS survey: A preview of the Universe in 56 colors",
    "year": "2021",
    "type": "journalArticle",
    "authors": [
      "S. Bonoli",
      "A. Marín-Franch",
      "J. Varela",
      "H. Vázquez Ramió",
      "L. R. Abramo",
      "A. J. Cenarro",
      "R. A. Dupke",
      "J. M. Vílchez",
      "D. Cristóbal-Hornillos",
      "R. M. González Delgado",
      "C. Hernández-Monteagudo",
      "C. López-Sanjuan",
      "D. J. Muniesa",
      "T. Civera",
      "A. Ederoclite",
      "A. Hernán-Caballero",
      "V. Marra",
      "P. O. Baqui",
      "A. Cortesi",
      "E. S. Cypriano",
      "S. Daflon",
      "A. L. de Amorim",
      "L. A. Díaz-García",
      "J. M. Diego",
      "G. Martínez-Solaeche",
      "E. Pérez",
      "V. M. Placco",
      "F. Prada",
      "C. Queiroz",
      "J. Alcaniz",
      "A. Alvarez-Candal",
      "J. Cepa",
      "A. L. Maroto",
      "F. Roig",
      "B. B. Siffert",
      "K. Taylor",
      "N. Benitez",
      "M. Moles",
      "L. Sodré",
      "S. Carneiro",
      "C. Mendes de Oliveira",
      "E. Abdalla",
      "R. E. Angulo",
      "M. Aparicio Resco",
      "A. Balaguera-Antolínez",
      "F. J. Ballesteros",
      "D. Brito-Silva",
      "T. Broadhurst",
      "E. R. Carrasco",
      "T. Castro",
      "R. Cid Fernandes",
      "P. Coelho",
      "R. B. de Melo",
      "L. Doubrawa",
      "A. Fernandez-Soto",
      "F. Ferrari",
      "A. Finoguenov",
      "R. García-Benito",
      "J. Iglesias-Páramo",
      "Y. Jiménez-Teja",
      "F. S. Kitaura",
      "J. Laur",
      "P. a. A. Lopes",
      "G. Lucatelli",
      "V. J. Martínez",
      "M. Maturi",
      "R. A. Overzier",
      "C. Pigozzo",
      "M. Quartin",
      "J. E. Rodríguez-Martín",
      "V. Salzano",
      "A. Tamm",
      "E. Tempel",
      "K. Umetsu",
      "L. Valdivielso",
      "R. von Marttens",
      "A. Zitrin",
      "M. C. Díaz-Martín",
      "G. López-Alegre",
      "A. López-Sainz",
      "A. Yanes-Díaz",
      "F. Rueda-Teruel",
      "S. Rueda-Teruel",
      "J. Abril Ibañez",
      "J. L Antón Bravo",
      "R. Bello Ferrer",
      "S. Bielsa",
      "J. M. Casino",
      "J. Castillo",
      "S. Chueca",
      "L. Cuesta",
      "J. Garzarán Calderaro",
      "R. Iglesias-Marzoa",
      "C. Íniguez",
      "J. L. Lamadrid Gutierrez",
      "F. Lopez-Martinez",
      "D. Lozano-Pérez",
      "N. Maícas Sacristán",
      "E. L. Molina-Ibáñez",
      "A. Moreno-Signes",
      "S. Rodríguez Llano",
      "M. Royo Navarro",
      "V. Tilve Rua",
      "U. Andrade",
      "E. J. Alfaro",
      "S. Akras",
      "P. Arnalte-Mur",
      "B. Ascaso",
      "C. E. Barbosa",
      "J. Beltrán Jiménez",
      "M. Benetti",
      "C. a. P. Bengaly",
      "A. Bernui",
      "J. J. Blanco-Pillado",
      "M. Borges Fernandes",
      "J. N. Bregman",
      "G. Bruzual",
      "G. Calderone",
      "J. M. Carvano",
      "L. Casarini",
      "J. Chaves-Montero",
      "A. L. Chies-Santos",
      "G. Coutinho de Carvalho",
      "P. Dimauro",
      "S. Duarte Puertas",
      "D. Figueruelo",
      "J. I. González-Serrano",
      "M. A. Guerrero",
      "S. Gurung-López",
      "D. Herranz",
      "M. Huertas-Company",
      "J. A. Irwin",
      "D. Izquierdo-Villalba",
      "A. Kanaan",
      "C. Kehrig",
      "C. C. Kirkpatrick",
      "J. Lim",
      "A. R. Lopes",
      "R. Lopes de Oliveira",
      "A. Marcos-Caballero",
      "D. Martínez-Delgado",
      "E. Martínez-González",
      "G. Martínez-Somonte",
      "N. Oliveira",
      "A. A. Orsi",
      "M. Penna-Lima",
      "R. R. R. Reis",
      "D. Spinoso",
      "S. Tsujikawa",
      "P. Vielva",
      "A. Z. Vitorelli",
      "J. Q. Xia",
      "H. B. Yuan",
      "A. Arroyo-Polonio",
      "M. L. L. Dantas",
      "C. A. Galarza",
      "D. R. Gonçalves",
      "R. S. Gonçalves",
      "J. E. Gonzalez",
      "A. H. Gonzalez",
      "N. Greisel",
      "F. Jiménez-Esteban",
      "R. G. Landim",
      "D. Lazzaro",
      "G. Magris",
      "R. Monteiro-Oliveira",
      "C. B. Pereira",
      "M. J. Rebouças",
      "J. M. Rodriguez-Espinosa",
      "S. Santos da Costa",
      "E. Telles"
    ],
    "venue": "Astronomy and Astrophysics",
    "doi": "10.1051/0004-6361/202038841",
    "url": "https://ui.adsabs.harvard.edu/abs/2021A&A...653A..31B/abstract",
    "summary": "This overview presents miniJPAS, a roughly one-square-degree AEGIS survey using the 56-filter J-PAS system plus broad bands. It releases images and a 64,000-source catalogue, reaches narrow-band depths of about 22–23.5 AB, and demonstrates better than 1% redshift accuracy to r=22.5, with about half of that sample reaching 0.3% precision."
  },
  {
    "key": "M3GLAMAD",
    "title": "The miniJPAS survey: Photometric redshift catalogue",
    "year": "2021",
    "type": "journalArticle",
    "authors": [
      "A. Hernán-Caballero",
      "J. Varela",
      "C. López-Sanjuan",
      "D. Muniesa",
      "T. Civera",
      "J. Chaves-Montero",
      "L. A. Díaz-García",
      "J. Laur",
      "C. Hernández-Monteagudo",
      "R. Abramo",
      "R. Angulo",
      "D. Cristóbal-Hornillos",
      "R. M. González Delgado",
      "N. Greisel",
      "A. Orsi",
      "C. Queiroz",
      "D. Sobral",
      "A. Tamm",
      "E. Tempel",
      "H. Vázquez-Ramió",
      "J. Alcaniz",
      "N. Benítez",
      "S. Bonoli",
      "S. Carneiro",
      "J. Cenarro",
      "R. Dupke",
      "A. Ederoclite",
      "A. Marín-Franch",
      "C. Mendes de Oliveira",
      "M. Moles",
      "L. Sodré",
      "K. Taylor",
      "E. S. Cypriano",
      "G. Martínez-Solaeche"
    ],
    "venue": "Astronomy and Astrophysics",
    "doi": "10.1051/0004-6361/202141236",
    "url": "https://ui.adsabs.harvard.edu/abs/2021A&A...654A.101H/abstract",
    "summary": "The paper describes the miniJPAS photometric-redshift pipeline, based on PSF-corrected forced photometry, iterative photometric-offset calibration, and customized LEPHARE templates across 60 bands. Validation with 5,266 spectra shows that formal Δχ² errors are underestimated, whereas the odds statistic reliably predicts absolute errors and outlier probability; an odds-selected sample reaches σNMAD=0.003 with a 5% outlier rate."
  },
  {
    "key": "UWDIKR5X",
    "title": "Tomographic constraints on gravity from angular redshift fluctuations in the late Universe",
    "year": "2021",
    "type": "journalArticle",
    "authors": [
      "Carlos Hernández-Monteagudo",
      "Jonás Chaves-Montero",
      "Raúl E. Angulo",
      "Giovanni Aricò"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnrasl/slab021",
    "url": "https://ui.adsabs.harvard.edu/abs/2021MNRAS.503L..62H",
    "summary": "This is the first cosmological application of angular redshift fluctuations (ARF), using BOSS LOWZ and CMASS galaxies to measure H/H0 fσ8 in more than 20 redshift slices from z=0.26 to 0.72. The measurements achieve about 7% precision per slice and, combined with Planck, constrain the growth index to γ=0.44 (+0.09/-0.07), consistent with general relativity within two standard deviations."
  },
  {
    "key": "JNTU9CLB",
    "title": "Scientific AI Approaches in Computational Cosmology",
    "year": "2020",
    "type": "report",
    "authors": [
      "Salman Habib",
      "Nesar Ramachandra",
      "Xiaofeng Dong",
      "Sandeep Madireddy",
      "Katrin Heitmann",
      "Jonas Chaves-Montero"
    ],
    "venue": "Snowmass2021 Letter of Interest",
    "doi": "",
    "url": "",
    "summary": "This Snowmass letter surveys opportunities for scientific AI in computational cosmology, including emulation, classification, inference, uncertainty quantification, incorporation of physical symmetries, and scalable use of emerging computing systems. It emphasizes verification, validation, and Bayesian/statistical rigor as distinguishing requirements of scientific applications."
  },
  {
    "key": "IXS97QHM",
    "title": "Surrogate modelling the Baryonic Universe - I. The colour of star formation",
    "year": "2020",
    "type": "journalArticle",
    "authors": [
      "Jonás Chaves-Montero",
      "Andrew Hearin"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnras/staa1230",
    "url": "http://adsabs.harvard.edu/abs/2020MNRAS.495.2088C",
    "summary": "Using GALAXPY with star-formation histories from UniverseMachine and IllustrisTNG, the paper isolates how star-formation history shapes present-day optical and near-infrared galaxy colours. Principal-component analysis reveals a nearly universal one-dimensional ‘SFH direction’ in colour space, controlled mainly by the fraction of stellar mass formed during the past billion years; metallicity, dust, and nebular emission move colours along distinguishable directions. The SFH direction aligns closely with the dominant axis of the observed SDSS colour distribution."
  },
  {
    "key": "9ED9W7A3",
    "title": "Density Weighted Angular Redshift Fluctuations: a New Cosmological Observable",
    "year": "2019",
    "type": "journalArticle",
    "authors": [
      "Carlos Hernandez-Monteagudo",
      "Jonas Chaves-Montero",
      "Raul E. Angulo"
    ],
    "venue": "arXiv e-prints",
    "doi": "",
    "url": "http://adsabs.harvard.edu/abs/2019arXiv191112056H",
    "summary": "The paper introduces density-weighted angular redshift fluctuations, δz(n), constructed by projecting galaxy redshifts through narrow redshift windows while weighting by galaxy density. Linear theory and simulations show that the observable responds to density and peculiar velocities, correlates strongly with the projected line-of-sight velocity field, is nearly independent of ordinary angular density for narrow windows, and is robust to redshift-independent additive and multiplicative number-count systematics. Fisher forecasts demonstrate that combining it with angular clustering substantially improves constraints on growth, galaxy bias, and primordial non-Gaussianity."
  },
  {
    "key": "NZZ4CSIR",
    "title": "High redshift galaxies in the ALHAMBRA survey. II. Strengthening the evidence of bright-end excess in UV luminosity functions at 2.5 ≤ z≤ 4.5 by PDF analysis",
    "year": "2018",
    "type": "journalArticle",
    "authors": [
      "K. Viironen",
      "C. López-Sanjuan",
      "C. Hernández-Monteagudo",
      "J. Chaves-Montero",
      "B. Ascaso",
      "S. Bonoli",
      "D. Cristóbal-Hornillos",
      "L. A. Díaz-García",
      "A. Fernández-Soto",
      "I. Márquez",
      "J. Masegosa",
      "M. Pović",
      "J. Varela",
      "A. J. Cenarro",
      "J. A. L. Aguerri",
      "E. Alfaro",
      "T. Aparicio-Villegas",
      "N. Benítez",
      "T. Broadhurst",
      "J. Cabrera-Caño",
      "F. J. Castander",
      "J. Cepa",
      "M. Cerviño",
      "R. M. González Delgado",
      "C. Husillos",
      "L. Infante",
      "V. J. Martínez",
      "M. Moles",
      "A. Molino",
      "A. del Olmo",
      "J. Perea",
      "F. Prada",
      "J. M. Quintana"
    ],
    "venue": "Astronomy and Astrophysics",
    "doi": "10.1051/0004-6361/201731797",
    "url": "http://adsabs.harvard.edu/abs/2018A%26A...614A.129V",
    "summary": "This study measures rest-frame ultraviolet luminosity functions of ALHAMBRA galaxies at redshifts 2.5–4.5 using the full redshift and magnitude probability distributions rather than point estimates. The large survey area provides strong leverage at the bright end, where the authors find more galaxies than typical broad-band studies but agreement with magnitude-selected spectroscopy; high measured bias values also support the high-redshift interpretation. The data leave open whether the luminosity function is best described by a double power law or a brighter Schechter form."
  },
  {
    "key": "R34A543C",
    "title": "Science Impacts of the SPHEREx All-Sky Optical to Near-Infrared Spectral Survey II: Report of a Community Workshop on the Scientific Synergies Between the SPHEREx Survey and Other Astronomy Observatories",
    "year": "2018",
    "type": "journalArticle",
    "authors": [
      "Olivier Doré",
      "Michael W. Werner",
      "Matthew L. N. Ashby",
      "Lindsey E. Bleem",
      "Jamie Bock",
      "Jennifer Burt",
      "Peter Capak",
      "Tzu-Ching Chang",
      "Jonás Chaves-Montero",
      "Christine H. Chen",
      "Francesca Civano",
      "I. Ilsedore Cleeves",
      "Asantha Cooray",
      "Brendan Crill",
      "Ian J. M. Crossfield",
      "Michael Cushing",
      "Sylvain de la Torre",
      "Tiziana DiMatteo",
      "Niv Dvory",
      "Cora Dvorkin",
      "Catherine Espaillat",
      "Simone Ferraro",
      "Douglas Finkbeiner",
      "Jenny Greene",
      "Jackie Hewitt",
      "David W. Hogg",
      "Kevin Huffenberger",
      "Hyun-Sung Jun",
      "Olivier Ilbert",
      "Woong-Seob Jeong",
      "Jennifer Johnson",
      "Minjin Kim",
      "J. Davy Kirkpatrick",
      "Theresa Kowalski",
      "Phil Korngut",
      "Jianshu Li",
      "Carey M. Lisse",
      "Meredith MacGregor",
      "Eric E. Mamajek",
      "Phil Mauskopf",
      "Gary Melnick",
      "Brice Ménard",
      "Mark Neyrinck",
      "Karin Öberg",
      "Alice Pisani",
      "Jennifer Rocca",
      "Mara Salvato",
      "Emmanuel Schaan",
      "Nick Z. Scoville",
      "Yong-Seon Song",
      "Daniel J. Stevens",
      "Ananth Tenneti",
      "Harry Teplitz",
      "Volker Tolls",
      "Stephen Unwin",
      "Meg Urry",
      "Benjamin Wandelt",
      "Benjamin F. Williams",
      "David Wilner",
      "Rogier A. Windhorst",
      "Scott Wolk",
      "Harold W. Yorke",
      "Michael Zemcov"
    ],
    "venue": "arXiv e-prints",
    "doi": "",
    "url": "http://adsabs.harvard.edu/abs/2018arXiv180505489D",
    "summary": "This community report surveys the legacy science enabled by SPHEREx’s planned all-sky 0.75–5 μm spectrophotometric data set, beyond its core themes of inflation, interstellar ices, and the extragalactic background light. It develops science cases and operational synergies with facilities including WISE, TESS, JWST, Euclid, and WFIRST/Roman, covering stars, galaxies, quasars, transients, solar-system targets, and diffuse emission. The report argues that the combination of broad spectral coverage, all-sky reach, and public products creates a uniquely reusable survey resource."
  },
  {
    "key": "7S5687WK",
    "title": "The effect of photometric redshift uncertainties on galaxy clustering and baryonic acoustic oscillations",
    "year": "2018",
    "type": "journalArticle",
    "authors": [
      "Jonás Chaves-Montero",
      "Raúl E. Angulo",
      "Carlos Hernández-Monteagudo"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnras/sty924",
    "url": "https://ui.adsabs.harvard.edu/abs/2018MNRAS.477.3892C",
    "summary": "Combining analytic calculations with 1,000 N-body simulations, the paper traces how sub-percent photometric-redshift errors alter the two-dimensional galaxy power spectrum and BAO information. Such errors suppress small-scale radial modes and increase shot-noise importance, but also reduce nonlinear redshift-space BAO smearing; the authors develop a template that recovers unbiased distances and analytic forecasts for spectro-photometric surveys."
  },
  {
    "key": "XUVSUF7Q",
    "title": "ELDAR, a new method to identify AGN in multi-filter surveys: the ALHAMBRA test case",
    "year": "2017",
    "type": "journalArticle",
    "authors": [
      "Jonás Chaves-Montero",
      "Silvia Bonoli",
      "Mara Salvato",
      "Natascha Greisel",
      "Luis A. Díaz-García",
      "Carlos López-Sanjuan",
      "Kerttu Viironen",
      "Alberto Fernández-Soto",
      "Mirjana Pović",
      "Begoña Ascaso",
      "Pablo Arnalte-Mur",
      "Josefa Masegosa",
      "Israel Matute",
      "Isabel Márquez",
      "A. Javier Cenarro",
      "L. Raul Abramo",
      "Alessandro Ederoclite",
      "Emilio J. Alfaro",
      "Antonio Marin-Franch",
      "Jesus Varela",
      "David Cristobal-Hornillos"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnras/stx2054",
    "url": "https://ui.adsabs.harvard.edu/abs/2017MNRAS.472.2085C",
    "summary": "The paper introduces ELDAR, an AGN-selection and redshift method that detects emission lines in medium- and narrow-band photometric data. Applied to ALHAMBRA, its two-line and three-line configurations identify 585 and 494 type-I AGN candidates, respectively, with redshift precision near 1%; at z > 2 the catalogues reach 85% and 77% completeness and show no galaxy contamination in the spectroscopic validation sample."
  },
  {
    "key": "ZNPEPSS7",
    "title": "Subhalo abundance matching and assembly bias in the EAGLE simulation",
    "year": "2016",
    "type": "journalArticle",
    "authors": [
      "Jonás Chaves-Montero",
      "Raul E. Angulo",
      "Joop Schaye",
      "Matthieu Schaller",
      "Robert A. Crain",
      "Michelle Furlong",
      "Tom Theuns"
    ],
    "venue": "Monthly Notices of the Royal Astronomical Society",
    "doi": "10.1093/mnras/stw1225",
    "url": "http://adsabs.harvard.edu/abs/2016MNRAS.460.3100C",
    "summary": "This paper tests subhalo abundance matching (SHAM) directly against galaxies in the EAGLE hydrodynamical simulation. It finds that the relaxed peak circular velocity, Vrelax, is the subhalo variable most tightly correlated with stellar mass: a Vrelax-based SHAM reproduces redshift-space clustering well and real-space clustering above roughly 2 Mpc, while overpredicting low-mass small-scale clustering because it assigns too many satellites to massive haloes. The analysis also shows that assembly bias changes EAGLE clustering by about 20%, with Vrelax capturing most, but not all, of that effect."
  },
  {
    "key": "8Q5PG6SM",
    "title": "WEAVE-QSO: A Massive Intergalactic Medium Survey for the William Herschel Telescope",
    "year": "2016",
    "type": "journalArticle",
    "authors": [
      "M. M. Pieri",
      "S. Bonoli",
      "J. Chaves-Montero",
      "I. Pâris",
      "M. Fumagalli",
      "J. S. Bolton",
      "M. Viel",
      "P. Noterdaeme",
      "J. Miralda-Escudé",
      "N. G. Busca",
      "H. Rahmani",
      "C. Peroux",
      "A. Font-Ribera",
      "S. C. Trager"
    ],
    "venue": "",
    "doi": "",
    "url": "http://adsabs.harvard.edu/abs/2016sf2a.conf..259P",
    "summary": "The paper outlines WEAVE-QSO, a planned spectroscopic survey of roughly 400,000 high-redshift quasars designed primarily to map the intergalactic medium in absorption. It describes complementary deep-wide and bright samples, selected mainly with J-PAS and Gaia, and forecasts applications to Lyα-forest BAO, dark energy, neutrino mass, warm dark matter, absorber physics, and gas around galaxies. The planned sample would deliver about 350,000 faint Lyα-forest spectra over the J-PAS overlap plus a high-signal-to-noise bright-quasar component."
  },
  {
    "key": "RPKN2Y59",
    "title": "High redshift galaxies in the ALHAMBRA survey . I. Selection method and number counts based on redshift PDFs",
    "year": "2015",
    "type": "journalArticle",
    "authors": [
      "K. Viironen",
      "A. Marín-Franch",
      "C. López-Sanjuan",
      "J. Varela",
      "J. Chaves-Montero",
      "D. Cristóbal-Hornillos",
      "A. Molino",
      "A. Fernández-Soto",
      "G. Vilella-Rojo",
      "B. Ascaso",
      "A. J. Cenarro",
      "M. Cerviño",
      "J. Cepa",
      "A. Ederoclite",
      "I. Márquez",
      "J. Masegosa",
      "M. Moles",
      "I. Oteo",
      "M. Pović",
      "J. A. L. Aguerri",
      "E. Alfaro",
      "T. Aparicio-Villegas",
      "N. Benítez",
      "T. Broadhurst",
      "J. Cabrera-Caño",
      "J. F. Castander",
      "A. Del Olmo",
      "R. M. González Delgado",
      "C. Husillos",
      "L. Infante",
      "V. J. Martínez",
      "J. Perea",
      "F. Prada",
      "J. M. Quintana"
    ],
    "venue": "Astronomy and Astrophysics",
    "doi": "10.1051/0004-6361/201425382",
    "url": "http://adsabs.harvard.edu/abs/2015A%26A...576A..25V",
    "summary": "This paper develops a probability-based method for selecting and statistically analysing high-redshift galaxies in ALHAMBRA’s multi-filter imaging. Rather than relying on dropout cuts or single photometric-redshift values, it uses integrated redshift probability distributions to build clean samples and sums those distributions to estimate population statistics. Applied in five bins from z≈2.5 to 4.5, the method yields ultraviolet number counts with particular sensitivity to the rare bright population."
  },
  {
    "key": "G6AXKQBV",
    "title": "Towards an ALHAMBRA quasar catalogue",
    "year": "2015",
    "type": "conferencePaper",
    "authors": [
      "J. Chaves-Montero",
      "S. Bonoli"
    ],
    "venue": "Highlights of Spanish Astrophysics VIII, XI Scientific Meeting of the Spanish Astronomical Society",
    "doi": "",
    "url": "https://ui.adsabs.harvard.edu/abs/2015hsa8.conf..365C",
    "summary": "This work develops an emission-line search in ALHAMBRA’s 20 contiguous optical and three infrared bands and applies it to roughly 430,000 sources. It produces 524 quasar candidates at z>0.8 over 2.79 square degrees; validation against known spectra yields no selected galaxies, photometric-redshift scatter σNMAD=0.010, and a 3.12% outlier fraction."
  }
];

const list = document.querySelector("#publication-list");
const search = document.querySelector("#publication-search");
const count = document.querySelector("#publication-count");
const filters = [...document.querySelectorAll("[data-year]")];
let activeYear = "all";

const esc = value => String(value ?? "").replace(/[&<>\"']/g, char => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));

function authorLine(authors) {
  const visible = authors.length > 7 ? [...authors.slice(0, 6), "et al."] : authors;
  return visible.map(name => /chaves-montero/i.test(name) ? `<strong>${esc(name)}</strong>` : esc(name)).join(", ");
}

function render() {
  const term = search.value.trim().toLowerCase();
  const shown = publications.filter(item => {
    const matchesYear = activeYear === "all" || item.year === activeYear || (activeYear === "older" && Number(item.year) <= 2020);
    const haystack = [item.title, item.summary, item.venue, ...item.authors].join(" ").toLowerCase();
    return matchesYear && (!term || haystack.includes(term));
  });
  count.textContent = `${shown.length} publication${shown.length === 1 ? "" : "s"}`;
  list.innerHTML = shown.map(item => {
    const href = item.doi ? `https://doi.org/${encodeURIComponent(item.doi)}` : item.url;
    return `<article class="publication-card">
      <div class="publication-meta"><span>${esc(item.year)}</span><span>${esc(item.venue || item.type.replace(/([A-Z])/g, " $1"))}</span></div>
      <h2>${href ? `<a href="${esc(href)}">${esc(item.title)}</a>` : esc(item.title)}</h2>
      <p class="publication-authors">${authorLine(item.authors)}</p>
      <p class="publication-summary">${esc(item.summary)}</p>
      ${href ? `<a class="publication-link" href="${esc(href)}">View publication <span aria-hidden="true">↗</span></a>` : ""}
    </article>`;
  }).join("");
}

search.addEventListener("input", render);
filters.forEach(button => button.addEventListener("click", () => {
  activeYear = button.dataset.year;
  filters.forEach(item => item.classList.toggle("active", item === button));
  render();
}));
render();
